### ISSUE TITLE
Donate on fdroid metadata

### ISSUE THREAD

**Issue by ghost** [StarGW-net/karma-firewall#11]
@StarGW-net 
* **your explicit consent is required** to add Donate ```https://www.stargw.net/money/?android```  given at https://github.com/StarGW-net/karma-firewall#readme in [fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/net.stargw.fok.yml)
* should i add for other 5 apps available on fdroid ```net.stargw.*``` also?
* fdroid [policy](https://gitlab.com/fdroid/admin/-/issues/417), [discussion 1](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13549#note_1508711371) and [discussion 2](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13533#note_1504648422) wrt to adding AuthorEmail, AuthorWebSite, Donate, etc..

**Comment by StarGW-net** [comment]
Yes I am fine with people giving me money :-)

Please add for the other apps.
