### ISSUE TITLE
Google Earth is reported as a new app every day

### ISSUE THREAD

**Issue by vrubleg** [StarGW-net/karma-firewall#15]
For some reason, the program shows a notification that it detected [Google Earth](https://play.google.com/store/apps/details?id=com.google.earth) as a new app, and it is repeated every day. For some reason the Karma FW can't remember that it already notified me about this app and keeps repeating it from time to time. Other apps are not affected.

Android 14, Samsung Galaxy S23+.

**Comment by StarGW-net** [comment]
This sounds like Samsung auto-sleeping apps.

Samsung sleeps an app (which is actually disables the app) but next time it is opened Samsung enables the app. Google Earth app probably gets called by some other Google app every day.

When an app is disabled (or deleted) Karma deletes all info about it. If it reappearts or get installed again Karma treats it as a new app.

I am working on v62 which handles disabled (sleeping) apps differently. I was waiting to see if I can roll in a fix for issue #14 as well, but I am having trouble reproducing that one.

Give me a day or so.

**Comment by vrubleg** [comment]
Seems like this doesn't happen anymore (but now I had to disable FW start alert, why would anybody need that?). Closing this ticket.

**Comment by StarGW-net** [comment]
The start notification alert is mandated for services that start in the background. Its Androids attempt to make sure the user knows an app is running in the background. Apps like WhatsApp etc are whitelisted by Google. Anyway like you have found you can disable the notification. But I have to code one in.
