### ISSUE TITLE
Connections from binaries

### ISSUE THREAD

**Issue by anpic** [StarGW-net/karma-firewall#17]
Are you planning to add connection blocking for system binaries for example such as ping or curl?
It works in firewalls like that NoRoot Firewall and PCAPdroid. There is a block even if you run binaries under the root.

**Comment by StarGW-net** [comment]
If you run the commands from the shell then this can be blocked by bocking the system app shell:

<img src="https://www.stargw.net/android/karma/images/fw-shell.png"
     alt="Firewall Shell"
     height="120">

This certainly works for anything run under ADB shell. Is this what you mean? If not please give a specific example.

I do not have a rooted phone to test on.

**Comment by anpic** [comment]
> If you run the commands from the shell then this can be blocked by blocking the system app shell

There is a block for all apps but..

> This certainly works for anything run under ADB shell. Is this what you mean? If not please give a specific example.

$ adb shell
device $ su
device # ping github.com
PING github.com (20.248.137.48) 56(84) bytes of data.
64 bytes from 20.248.137.48: icmp_seq=1 ttl=112 time=712 ms
64 bytes from 20.248.137.48: icmp_seq=2 ttl=112 time=712 ms
64 bytes from 20.248.137.48: icmp_seq=3 ttl=112 time=737 ms
64 bytes from 20.248.137.48: icmp_seq=4 ttl=112 time=660 ms

**Comment by StarGW-net** [comment]
As I mentioned, I do not have a rooted phone to try this on.

After su what is the output of these commands?

ps -aef
id

And if you do:

ping github.com &

What is the output of:

ps -aef
id

Thanks

**Comment by anpic** [comment]
> After su what is the output of these commands?

Any applications running under root have its id: 0

**Comment by anpic** [comment]
I'm starting to guess why it's like this :)
Are you filtering by UIDs?
Then you need to add a separate item in the settings to block 0 and 1-9999 uids for system binaries, services and applications.

**Comment by anpic** [comment]
See how AFWall and PCAPdroid works with the system uids.
There are even unknowns uids being tracked as negative numbers.

**Comment by anpic** [comment]
https://github.com/ukanth/afwall/blob/beta/app/src/main/java/dev/ukanth/ufirewall/Api.java#L1351

**Comment by anpic** [comment]
Here is the main:
https://github.com/emanuele-f/PCAPdroid/blob/master/app/src/main/java/com/emanuelef/remote_capture/AppsResolver.java

**Comment by StarGW-net** [comment]
I'll take a look.

The VPN works using addAllowedApplication(packageName) so I need a package name. Under the hood Android VPN works on UID so if you firewall using packageName a system app, and other package with the same UID will be firewalled. But the API does not allow me to VPN/Firewall by UID directly only Package Name.

https://developer.android.com/reference/android/net/VpnService.Builder#addAllowedApplication(java.lang.String)

adb shell pm list packages --uid 0

Returns nothing.

I currently get Installed packages (insluding system) by:

`List<PackageInfo> packageInfoList = Global.getContext().getPackageManager().getInstalledPackages(0);`

Then:

`packageInfo = Global.getContext().getPackageManager().getPackageInfo(packageName, PackageManager.GET_PERMISSIONS);`

I'll have a closer look at the code examples you sent and see how others cope with this.

**Comment by anpic** [comment]
> But the API does not allow me to VPN/Firewall by UID directly only Package Name.

That's the bad news :(
System uids are just numbers.
So it turns out that it's impossible to create a full-fledged firewall without Internet permission :(

**Comment by anpic** [comment]
Probably PCAPdroid runs itself as VPN-service and works as a local MITM to filter all traffic

**Comment by anpic** [comment]
Check this again just in case
https://developer.android.com/reference/android/content/pm/PackageManager#getNameForUid(int)
https://developer.android.com/reference/android/content/pm/PackageManager#getPackagesForUid(int)

**Comment by anpic** [comment]
It's unlikely to help but suddenly ;)
And so apparently another meanness from Google :(

**Comment by StarGW-net** [comment]
I tried and the following returns null:

getContext().getPackageManager().getNameForUid(0);

I do not think there is a way for a non-root firewall, or a firewall which does not inspect packets to block binaries run as root.

**Comment by anpic** [comment]
> I do not think there is a way for a non-root firewall, or a firewall which does not inspect packets to block binaries run as root.

I wrote about this above
Thanks to Google :(
