### ISSUE TITLE
Some apps don't appear in list

### ISSUE THREAD

**Issue by VA1DER** [StarGW-net/karma-firewall#18]
Simple Gallery Pro (available on F-Droid) does not appear on the list of apps that Karma can block.  Neither does Simple SMS.  Perhaps the way they generate shortcuts.  There may be others, I haven't cross referenced every app yet.

**Comment by gbdomubpkm** [comment]
Isn't it simply because these apps basically have no connection to the internet ? So they don't appear in the list.

**Comment by StarGW-net** [comment]
Yes, Karma ignores apps that do not have network permissions.

I use Simple Gallery myself, and if you go to Settings -> Apps -> Gallery -> Mobile Data you will see it has used zero data.
